### ISSUE TITLE
Cannot be installed

### ISSUE THREAD

**Issue by pforrmi** [Aietes/node-red-contrib-harmony#11]
In version 0.8.14 it can not be installed. It ends with an error.
Does anyone else have problems?

See my log.
[2018-05-01T10_22_28_024Z-debug.log](https://github.com/Aietes/node-red-contrib-harmony/files/1963523/2018-05-01T10_22_28_024Z-debug.log)

**Comment by Aietes** [comment]
I just tested it with the same version of both node-red and this package, it works fine for me. I just updated this package, maybe try with the new version.
