### ISSUE TITLE
npm ERR! code ENOGIT

### ISSUE THREAD

**Issue by K-RAD** [Aietes/node-red-contrib-harmony#12]
Trying to install, getting following error. Maybe the documentation should be updated with additional prerequisites?

npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

**Comment by Aietes** [comment]
This seems to be a problem with your local npm installation, not this library. Please look for the documentation on how to set up npm on your respective machine, e.g. https://github.com/npm/npm/wiki/Troubleshooting.  From the error message, it seems you need to install git: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git.
