### ISSUE TITLE
Error: Cannot find module 'autobind-decorator'

### ISSUE THREAD

**Issue by bkanuka** [Aietes/node-red-contrib-harmony#14]
This error appears in logs when installing the module through the node-red interface. I am also unable to search for Harmony hubs (which may or may not be related)

**Comment by lespatots** [comment]
I had the same. Try this install

npm install autobind-decorator

 It Fixed it for me

**Comment by Aietes** [comment]
Thank you for reporting this! It seems to be is a dependency of the underlying library @harmonyhub. I'll check with @AirBorne04 and find a fix.

**Comment by lespatots** [comment]
npm install autobind-decorator fixes it, but I guess this should be part of the node install. In the meantime you could just record the dependency.

**Comment by Aietes** [comment]
With regards to searching for Harmony hubs, since I also switched out the discover library, I think it's related to that. May I ask in what environment you run Node-RED? OS, version, in a docker container?

**Comment by lespatots** [comment]
I relise you didn't ask this to me but. I have two Harmony hubs and it only finds one. My Node-red is running on a raspberry pi without docker at present. I'm at the latest version 0.17.5?

I haven't been able to test any Harmony operations yet so I'm not sure whether setting the IP for the second hub is effective!

**Comment by Aietes** [comment]
I released a temporary fix for the missing library, version 1.2.1 now includes the autobind-decorator, until it's added as dependency to the underlying library.

**Comment by Aietes** [comment]
I moved to conversation re searching for Harmony hubs to a new issue #15. @lespatots currently the extension just takes the first Hub it finds. I'll opened an enhancement issue #16 to support multiple hubs. I actually have two myself :) Entering the IP of the second Hub manually will work though.

**Comment by AirBorne04** [comment]
I fixed the dependency issue right away, should work now.

**Comment by Aietes** [comment]
Thanks to @AirBorne04 this is fixed, released version 1.2.2
