### ISSUE TITLE
Unable to search for Harmony hubs 

### ISSUE THREAD

**Issue by Aietes** [Aietes/node-red-contrib-harmony#15]
@bkanuka reported that it's not possible to search for Harmony hubs. Listing this a separate issue from #14.

**Comment by AirBorne04** [comment]
I guess the problem was searching for hubs, but rather the missing option to choose from multiple discovered. As described here #16  is that correct @bkanuka?

**Comment by Aietes** [comment]
addressed in relase v1.2.4
