### ISSUE TITLE
Port 5000 in use 

### ISSUE THREAD

**Issue by bakman2** [Aietes/node-red-contrib-harmony#19]
I am running node-red (docker) on a synology which uses port 5000 for its webinterface, when trying to add a harmony hub, node-red crashes. I've changed the source code from 5002-6000 which works. A smaller/less exotic range could avoid this ?

**Comment by supagold** [comment]
Same here. My hubs have assigned IPs, so adding them manually by IP worked, but it would be nice if we could skip port 5000.

**Comment by Aietes** [comment]
Actually, the extension does scan for a free port using netstat, and not use a port that is already in use. It doesn't matter much in docker though, as port detection doesn't work anyway, as broadcasting doesn't work in containers. I'll adjust the starting port to 5002, to avoid the crash.

**Comment by Aietes** [comment]
To clarify, the extension works in a docker container, I use it in docker myself, but the IP detection of a hub will not work, you'll need to enter the IP manually.

**Comment by Aietes** [comment]
Fixed in 1.2.6
