### ISSUE TITLE
Observe more than activities, button presses.

### ISSUE THREAD

**Issue by AUyttendaele** [Aietes/node-red-contrib-harmony#20]
Hi, would it be possible to observe button presses.

I would like to assign unused buttons to lights. E.g. the coloured buttons. Or the light buttons at the bottom.

Thanks. Other than that it is working flawlessly.

**Comment by Aietes** [comment]
Unfortunately, this is not possible to my knowledge, there is no documented / known event that would allow for listening to button events on the Harmony hub.
