### ISSUE TITLE
Changing Hub doesn't change Activities 

### ISSUE THREAD

**Issue by supagold** [Aietes/node-red-contrib-harmony#21]
I notice that changing to a different Hub in a node, then refreshing Activities doesn't pull Activities from the new Hub. Selecting the new Hub, closing the node, then reopening and refreshing Activities does work to pull the correct Activities.

**Comment by Aietes** [comment]
Yes, the hub change is only saved on closing the node. I'll change it, so it behaves as expected.

**Comment by Aietes** [comment]
Fixed in 1.2.6
