### ISSUE TITLE
 H observe stops sending data after one day

### ISSUE THREAD

**Issue by PLCHome** [Aietes/node-red-contrib-harmony#22]
After deploying the flow, H Observe will work for some time. But after some time, no data will be forwarded. Most of the time it happens the next day.

Is there a way to check the connection?

**Comment by PLCHome** [comment]
Sorry, I found the cause. It was because NODE-Red was restarted due to another NODE.

**Comment by grexxen** [comment]
Hi there, 
I have the same problem. After deploying H Observe works fine, but after some time it stops sending data. Until now I did not find the cause. How did you find the problem?
