### ISSUE TITLE
MAX_CLIENTS=6 ERROR

### ISSUE THREAD

**Issue by lespatots** [Aietes/node-red-contrib-harmony#4]
I think this suffers from the problem reported here swissmanu/harmonyhubjs-client
 and affecting Homebridge as well as Node-Red. The error crashes Node-Red!!

**Comment by Aietes** [comment]
Unfortunately I currently see no way to catch or prevent this error on my side. I think it's even deeper than swissmanus library, as the exception comes from an underlying library.

**Comment by lespatots** [comment]
I am sure you are right. I raised the issue more as a warning at this time. Whenever this is fixed, I guess it needs testing. Strangely this problem does not seem to affect Home Assistant!

**Comment by guevara777** [comment]
Hi. Great work. Big Thanks to the developer.

Is there any progress on this issue? My Node-Red Setup keeps crashing after 1-2 days and i have to restart it manually.

**Comment by Bodge-IT** [comment]
I'm getting this too, destabilising my NR.  When the crash occurs I get errors from js code in this location:
/.node-red/node_modules/node-red-contrib-harmony/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/
Seems to be installing stuff several layers deep, is that correct?  Will these nodes themselves be updated with npm outdated?

**Comment by K-RAD** [comment]
Same issue here, but it crashes my node-red very often when I try to deploy

**Comment by Aietes** [comment]
This is due to an underlying npm package. I'll soon replace that dependency with an updated library, which will hopefully solve this issue.

**Comment by lespatots** [comment]
That would be just brilliant, so many people trip over this error.

**Comment by K-RAD** [comment]
Yeah, I had to remove the plugin.. Until this is ready, is there any way to start an activity by url POST? :)

**Comment by lespatots** [comment]
Not something I’m familiar with. I would normally trigger an activity through MQTT? Would that work for you?

**Comment by Aietes** [comment]
I committed a new version, which is using Airborne's new and improved @harmonyhub libraries. This should solve this issue, and make the extension stable.

**Comment by lespatots** [comment]
Hi,

Just installed this. Get an error as follows:

'node-red-contrib-harmony:harmony-server : Error: Cannot find module 'autobind-decorator' (line:1)'

I guess I miss a library?

Richard
