### ISSUE TITLE
Can't load activities / commands from harmony hub

### ISSUE THREAD

**Issue by tbowmo** [Aietes/node-red-contrib-harmony#5]
Somehow I can't get my node-red to load any activities / commands from my harmony hub (it has worked before though)

I'm using node-red 0.15.1, harmony hub sw version is 4.12.36

Adding H-Command, then add my harmony (by entering ip address manually, search functionality doesn't work either). IP address is static. If I start by pressing the search icon besides activity, then it just shows "Loading activities" forever..

As mentioned, I know that it has been working before, but I have started my node-red setup from scratch, to clear up some other details.. And now it doesn't work..

**Comment by Aietes** [comment]
Were you able to track down the issue? I have to assume that it is something with your specific setup, as this isn't a problem with other users.

**Comment by klein0r** [comment]
I have the same issue. Isn't there a possibility to provide a username and a password?
