### ISSUE TITLE
Nodes quit working

### ISSUE THREAD

**Issue by rgerrans** [Aietes/node-red-contrib-harmony#8]
In the last couple of days I've noticed that my harmony nodes no longer work.  I verified that the harmony-server node reports back that it is connected to a valid server.  But when I change an activity on the hub it's not producing any output from the H Observe node.  Similarly, I verified that my h-activity node is pulling the id associated with an activity but sending a trigger message to the node is not turning on or off the activity.  I'm not seeing any error messages generated in my log output.

**Comment by rgerrans** [comment]
Nevermind, a Node-RED restart seemed to have solved the issue

**Comment by bkanuka** [comment]
I had a similar issue. Yes, restarting Node Red worked, but I believe this is still a bug. There is no indication that communication with the Harmony has stopped - it just silently fails.

**Comment by rgerrans** [comment]
I just reopened this since it's not just me and mine did it again.  Wonder if it's a Node-RED issue or the node.js that it wraps around.  When I have time in the next week or so, I'm going to just try to go straight to the node.js and see if that stabalizes it.

Thanks.

**Comment by bkanuka** [comment]
Last time this problem happened, I sent a command to harmony using a command node, and I believe that was enough to reestablish the connection. My harmony observe node then worked again.

Only light evidence at this point though - I haven't had the problem again to test.

**Comment by rocklobster42195** [comment]
Same problem here. Restarting Node Red doesn't help.

**Comment by Aietes** [comment]
Should be fixed in latest version thanks to your contribution!
